targets:
  $default:
    builders:
      flutter_gen_runner:
        options:
          output: lib/config/gen/
      json_serializable:
        generate_for:
          include:
            - "lib/**/entities/*.dart"
        options:
          checked: true
          field_rename: snake
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
