name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  yumemi_lints: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
